### ISSUE TITLE
Dependency BusIO missing

### ISSUE THREAD

**Issue by kopp** [adafruit/Adafruit_LSM303_Accel#3]
The dependency to Adafruits BusIO is missing in the description.

- Arduino board:  Uno (does not matter)

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.9 (does not matter)

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

1. Install this library (v1.1.0)
1. Install Adafruit Unified Sensor (v1.0.3)
1. Create a minimal example that just contains

```
#include <Adafruit_LSM303_Accel.h>
#include <Adafruit_Sensor.h>
#include <Wire.h>

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

You will get a compilation error:

> fatal error: Adafruit_BusIO_Register.h: No such file or directory

- Proposed fix:

Add the library [BusIO](https://github.com/adafruit/Adafruit_BusIO) to the list of dependencies of this library.

**Comment by siddacious** [comment]
Thanks! I'll probably get to this Monday

**Comment by siddacious** [comment]
Thanks for the bug report; the readme has been updated with more complete instructions and a link to the guide with more detail

**Comment by kopp** [comment]
thank you for the fix!
