### ISSUE TITLE
Raw readings?

### ISSUE THREAD

**Issue by adamgarbo** [adafruit/Adafruit_LSM303_Accel#8]
Hi there,

I'm working with the LSM303AGR and I noticed that the unified driver doesn't make the raw readings accessible. This seems to be due to the functions being private:

```
'lsm303AccelData Adafruit_LSM303_Accel_Unified::raw' is private within this context
``` 

The LIS2MDL library adds a struct to store the raw readings, which are easily accessed:
https://github.com/adafruit/Adafruit_LIS2MDL/blob/0230c02c87fe5f528b713f222eccc20532316253/Adafruit_LIS2MDL.h#L111

Is it possible to access or enable raw measurements for the LSM303 accelerometer? This would be very helpful for pitch/roll/tilt-compensated heading calculations.

Cheers,
Adam

**Comment by ladyada** [comment]
we dont think you want that, the readings need to be scaled!

**Comment by adamgarbo** [comment]
Roger! I had been previously manually scaling the raw accelerometer data (based on Jim Remington's code) but after digging deeper I see that the LSM303 Accel and Adafruit Sensor libraries are doing the work for me!
